# Generated by Django 4.0 on 2022-11-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_ages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='ages',
            new_name='age',
        ),
    ]
