# Generated by Django 3.2 on 2022-11-03 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_ages_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 11, 3, 20, 14, 13, 197161, tzinfo=utc), max_length=25),
            preserve_default=False,
        ),
    ]
