# Generated by Django 3.2 on 2022-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20221105_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
