# Generated by Django 3.2 on 2022-11-14 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_candidate_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 18, 52, 30, 730679, tzinfo=utc), verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='pending', max_length=50, null=True),
        ),
    ]
