# Generated by Django 3.2 on 2022-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20221114_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(blank=True, upload_to='resume', verbose_name='Resume'),
        ),
    ]
